"""
nakshatra_data.py — Comprehensive Nakshatra reference data.
============================================================
Contains NAKSHATRA_DETAIL: a dictionary keyed by the 27 nakshatra names
with complete traditional attributes including deity, lord, symbol, yoni,
gana, guna, tattva, caste, nadi, temperament, pada details, remedies,
activation practices, shakti, and more.

All names match the canonical list in core/constants.NAKSHATRAS_27.
This file is self-contained with no external imports.
"""
from __future__ import annotations

NAKSHATRA_DETAIL: dict[str, dict] = {

    # ─────────────────────────────────────────────────────────────
    # 1. ASHWINI  (0°00' – 13°20' Aries)
    # ─────────────────────────────────────────────────────────────
    "Ashwini": {
        "deity": "Ashwini Kumaras",
        "deity_hi": "अश्विनी कुमार",
        "lord": "Ketu",
        "symbol": "Horse Head",
        "symbol_hi": "घोड़े का सिर",
        "animal_yoni": "Horse (Male)",
        "animal_yoni_hi": "अश्व (पुरुष)",
        "gana": "Deva",
        "guna": "Sattva",
        "tattva": "Earth",
        "caste": "Vaishya",
        "gender": "Male",
        "nadi": "Aadi",
        "color": "Red",
        "bird": "Swan",
        "tree": "Poison Nut Tree",
        "tree_botanical": "Strychnos nux-vomica",
        "body_part": "Knees",
        "direction": "South",
        "motivation": "Dharma",
        "temperament": "Light (Laghu/Kshipra)",
        "pada_syllables": ["Chu", "Che", "Cho", "La"],
        "pada_details": [
            {"pada": 1, "navamsa_sign": "Aries", "planet": "Mars", "quality": "Pioneer energy, courage and initiative"},
            {"pada": 2, "navamsa_sign": "Taurus", "planet": "Venus", "quality": "Grounded healing, material resourcefulness"},
            {"pada": 3, "navamsa_sign": "Gemini", "planet": "Mercury", "quality": "Intellectual curiosity, communication of knowledge"},
            {"pada": 4, "navamsa_sign": "Cancer", "planet": "Moon", "quality": "Emotional healing, nurturing compassion"},
        ],
        "activation": "Worship the Ashwini Kumaras at dawn. Practice early morning meditation facing east. Engage in healing arts or volunteer at health camps. Offer red flowers and chant Ketu mantras.",
        "remedy": {
            "deity_worship": "Worship Ashwini Kumaras with red flowers at sunrise",
            "mantra": "Om Ashwini Kumarabhyam Namah",
            "gemstone": "Cat's Eye (Lehsunia)",
            "donation": "Donate blankets and medicines to the needy",
            "fasting": "Tuesday",
            "color_therapy": "Red",
            "plant_remedy": "Use Strychnos nux-vomica bark in small Ayurvedic preparations under guidance",
        },
        "special_power": "Shidravyapani Shakti (power to quickly reach and heal)",
        "description": "Ashwini is the star of transport and swift healing. Its natives are fast-acting pioneers with natural medical or therapeutic abilities.",
        "description_hi": "अश्विनी तीव्र गति और चिकित्सा का नक्षत्र है। इसके जातक तेज़, साहसी और स्वाभाविक चिकित्सक होते हैं।",
    },

    # ─────────────────────────────────────────────────────────────
    # 2. BHARANI  (13°20' – 26°40' Aries)
    # ─────────────────────────────────────────────────────────────
    "Bharani": {
        "deity": "Yama",
        "deity_hi": "यम",
        "lord": "Venus",
        "symbol": "Yoni (Female Reproductive Organ)",
        "symbol_hi": "योनि",
        "animal_yoni": "Elephant (Male)",
        "animal_yoni_hi": "गज (पुरुष)",
        "gana": "Manushya",
        "guna": "Rajas",
        "tattva": "Earth",
        "caste": "Kshatriya",
        "gender": "Female",
        "nadi": "Madhya",
        "color": "Red",
        "bird": "Crow",
        "tree": "Indian Gooseberry (Amla)",
        "tree_botanical": "Emblica officinalis",
        "body_part": "Head/Forehead",
        "direction": "West",
        "motivation": "Artha",
        "temperament": "Fierce (Ugra/Krura)",
        "pada_syllables": ["Li", "Lu", "Le", "Lo"],
        "pada_details": [
            {"pada": 1, "navamsa_sign": "Leo", "planet": "Sun", "quality": "Creative self-expression, authoritative presence"},
            {"pada": 2, "navamsa_sign": "Virgo", "planet": "Mercury", "quality": "Analytical service, attention to detail"},
            {"pada": 3, "navamsa_sign": "Libra", "planet": "Venus", "quality": "Harmonious relationships, artistic sensibility"},
            {"pada": 4, "navamsa_sign": "Scorpio", "planet": "Mars", "quality": "Intense transformation, deep research"},
        ],
        "activation": "Worship Lord Yama for fearlessness regarding mortality. Perform rituals during Bharani days. Practice restraint and self-discipline. Offer red hibiscus flowers and perform Venus-related rituals on Fridays.",
        "remedy": {
            "deity_worship": "Worship Yama Dharmaraja with red flowers and sesame seeds",
            "mantra": "Om Yamaya Namah",
            "gemstone": "Diamond or White Sapphire",
            "donation": "Donate food, clothing, and sugar to the poor",
            "fasting": "Friday",
            "color_therapy": "Red",
            "plant_remedy": "Consume Amla (Indian Gooseberry) regularly for vitality",
        },
        "special_power": "Apabharani Shakti (power to carry things away, to cleanse and remove)",
        "description": "Bharani embodies the cycle of birth, death, and transformation. Its natives carry tremendous creative and procreative energy with a sense of duty and moral responsibility.",
        "description_hi": "भरणी जन्म, मृत्यु और परिवर्तन का नक्षत्र है। इसके जातक प्रचंड सृजनात्मक ऊर्जा और कर्तव्य भावना रखते हैं।",
    },

    # ─────────────────────────────────────────────────────────────
    # 3. KRITTIKA  (26°40' Aries – 10°00' Taurus)
    # ─────────────────────────────────────────────────────────────
    "Krittika": {
        "deity": "Agni",
        "deity_hi": "अग्नि",
        "lord": "Sun",
        "symbol": "Razor/Flame",
        "symbol_hi": "उस्तरा/अग्नि शिखा",
        "animal_yoni": "Goat (Female)",
        "animal_yoni_hi": "भेड़ (स्त्री)",
        "gana": "Rakshasa",
        "guna": "Rajas",
        "tattva": "Water",
        "caste": "Brahmin",
        "gender": "Female",
        "nadi": "Antya",
        "color": "White",
        "bird": "Peacock",
        "tree": "Fig Tree (Gular)",
        "tree_botanical": "Ficus racemosa",
        "body_part": "Hips/Waist/Crown",
        "direction": "North",
        "motivation": "Kama",
        "temperament": "Mixed (Mishra/Sadharana)",
        "pada_syllables": ["A", "I", "U", "E"],
        "pada_details": [
            {"pada": 1, "navamsa_sign": "Sagittarius", "planet": "Jupiter", "quality": "Philosophical fire, righteous leadership"},
            {"pada": 2, "navamsa_sign": "Capricorn", "planet": "Saturn", "quality": "Disciplined ambition, structured authority"},
            {"pada": 3, "navamsa_sign": "Aquarius", "planet": "Saturn", "quality": "Humanitarian vision, reform-oriented thinking"},
            {"pada": 4, "navamsa_sign": "Pisces", "planet": "Jupiter", "quality": "Spiritual purification, compassionate strength"},
        ],
        "activation": "Perform Agni Homa (fire ritual). Light a ghee lamp daily. Worship Lord Kartikeya (Murugan). Practice Sun salutations at dawn. Offer white flowers to Agni during Krittika days.",
        "remedy": {
            "deity_worship": "Worship Agni Deva with ghee lamp offerings and perform Havan",
            "mantra": "Om Agnaye Namah",
            "gemstone": "Ruby (Manik)",
            "donation": "Donate wheat, jaggery, and red cloth",
            "fasting": "Sunday",
            "color_therapy": "White",
            "plant_remedy": "Use fig (Gular) fruit in daily diet for digestive and spiritual balance",
        },
        "special_power": "Dahana Shakti (power to burn and purify)",
        "description": "Krittika is the star of fire and purification. Its natives are sharp, critical, and possess a burning determination to cut through falsehood and achieve clarity.",
        "description_hi": "कृत्तिका अग्नि और शुद्धिकरण का नक्षत्र है। इसके जातक तीक्ष्ण, आलोचनात्मक और सत्य के प्रति दृढ़ होते हैं।",
    },

    # ─────────────────────────────────────────────────────────────
    # 4. ROHINI  (10°00' – 23°20' Taurus)
    # ─────────────────────────────────────────────────────────────
    "Rohini": {
        "deity": "Brahma",
        "deity_hi": "ब्रह्मा",
        "lord": "Moon",
        "symbol": "Chariot/Ox Cart",
        "symbol_hi": "बैलगाड़ी/रथ",
        "animal_yoni": "Serpent (Male)",
        "animal_yoni_hi": "सर्प (पुरुष)",
        "gana": "Manushya",
        "guna": "Rajas",
        "tattva": "Earth",
        "caste": "Shudra",
        "gender": "Female",
        "nadi": "Antya",
        "color": "White",
        "bird": "Owl",
        "tree": "Jamun (Java Plum)",
        "tree_botanical": "Syzygium cumini",
        "body_part": "Forehead/Calves/Shins",
        "direction": "East",
        "motivation": "Moksha",
        "temperament": "Fixed (Dhruva)",
        "pada_syllables": ["O", "Va", "Vi", "Vu"],
        "pada_details": [
            {"pada": 1, "navamsa_sign": "Aries", "planet": "Mars", "quality": "Dynamic creativity, passionate expression"},
            {"pada": 2, "navamsa_sign": "Taurus", "planet": "Venus", "quality": "Peak material abundance, sensory pleasure"},
            {"pada": 3, "navamsa_sign": "Gemini", "planet": "Mercury", "quality": "Artistic communication, versatile talent"},
            {"pada": 4, "navamsa_sign": "Cancer", "planet": "Moon", "quality": "Deep emotional nurturing, maternal warmth"},
        ],
        "activation": "Worship Lord Brahma. Nurture plants and maintain a garden. Use dairy products (milk, ghee) in rituals. Chant Moon mantras on Mondays. Wear white and adorn yourself beautifully.",
        "remedy": {
            "deity_worship": "Worship Brahma with lotus flowers and offer milk to Shiva Linga",
            "mantra": "Om Brahmane Namah",
            "gemstone": "Pearl (Moti)",
            "donation": "Donate white clothes, rice, and silver",
            "fasting": "Monday",
            "color_therapy": "White",
            "plant_remedy": "Eat Jamun fruit regularly; plant a Jamun tree near your home",
        },
        "special_power": "Rohana Shakti (power of growth and creation)",
        "description": "Rohini is the most fertile and creative nakshatra, beloved of the Moon. Its natives are attractive, artistic, and possess a magnetic charm with a deep love for beauty and comfort.",
        "description_hi": "रोहिणी सबसे उर्वर और सृजनशील नक्षत्र है, चंद्रमा का प्रिय। इसके जातक आकर्षक, कलात्मक और सौंदर्यप्रेमी होते हैं।",
    },

    # ─────────────────────────────────────────────────────────────
    # 5. MRIGASHIRA  (23°20' Taurus – 6°40' Gemini)
    # ─────────────────────────────────────────────────────────────
    "Mrigashira": {
        "deity": "Soma",
        "deity_hi": "सोम",
        "lord": "Mars",
        "symbol": "Deer Head",
        "symbol_hi": "मृग का सिर",
        "animal_yoni": "Serpent (Female)",
        "animal_yoni_hi": "सर्पिणी (स्त्री)",
        "gana": "Deva",
        "guna": "Sattva",
        "tattva": "Earth",
        "caste": "Vaishya",
        "gender": "Neutral",
        "nadi": "Madhya",
        "color": "Silver/Grey",
        "bird": "Rooster",
        "tree": "Khadira/Cutch Tree",
        "tree_botanical": "Acacia catechu",
        "body_part": "Eyes",
        "direction": "South",
        "motivation": "Moksha",
        "temperament": "Soft (Mridu)",
        "pada_syllables": ["Ve", "Vo", "Ka", "Ki"],
        "pada_details": [
            {"pada": 1, "navamsa_sign": "Leo", "planet": "Sun", "quality": "Confident exploration, creative seeking"},
            {"pada": 2, "navamsa_sign": "Virgo", "planet": "Mercury", "quality": "Analytical research, intellectual pursuit"},
            {"pada": 3, "navamsa_sign": "Libra", "planet": "Venus", "quality": "Social charm, quest for beauty and harmony"},
            {"pada": 4, "navamsa_sign": "Scorpio", "planet": "Mars", "quality": "Deep investigation, emotional intensity in seeking"},
        ],
        "activation": "Worship Soma (Moon deity). Spend time in nature observing deer or wildlife. Engage in fragrance-making or perfumery. Practice gentle, seeking meditation. Walk in moonlight on Mrigashira days.",
        "remedy": {
            "deity_worship": "Worship Soma Deva with white sandalwood paste and Soma offerings",
            "mantra": "Om Somaya Namah",
            "gemstone": "Red Coral (Moonga)",
            "donation": "Donate perfumes, scented items, and silver ornaments",
            "fasting": "Tuesday",
            "color_therapy": "Silver/Grey",
            "plant_remedy": "Use Khadira (Catechu) bark decoction for skin health and purification",
        },
        "special_power": "Prinana Shakti (power to give fulfillment and joy)",
        "description": "Mrigashira is the searching star, symbolized by the ever-curious deer. Its natives are gentle seekers, always in pursuit of beauty, knowledge, and new experiences.",
        "description_hi": "मृगशिरा खोज और जिज्ञासा का नक्षत्र है। इसके जातक कोमल, सौंदर्यप्रेमी और नए अनुभवों के खोजी होते हैं।",
    },

    # ─────────────────────────────────────────────────────────────
    # 6. ARDRA  (6°40' – 20°00' Gemini)
    # ─────────────────────────────────────────────────────────────
    "Ardra": {
        "deity": "Rudra",
        "deity_hi": "रुद्र",
        "lord": "Rahu",
        "symbol": "Teardrop/Diamond",
        "symbol_hi": "आँसू की बूंद/हीरा",
        "animal_yoni": "Dog (Female)",
        "animal_yoni_hi": "कुतिया (स्त्री)",
        "gana": "Manushya",
        "guna": "Tamas",
        "tattva": "Water",
        "caste": "Shudra",
        "gender": "Female",
        "nadi": "Aadi",
        "color": "Green",
        "bird": "Eagle",
        "tree": "Agar/Eaglewood",
        "tree_botanical": "Aquilaria agallocha",
        "body_part": "Skull/Crown",
        "direction": "West",
        "motivation": "Kama",
        "temperament": "Sharp (Tikshna)",
        "pada_syllables": ["Ku", "Gha", "Ng", "Chha"],
        "pada_details": [
            {"pada": 1, "navamsa_sign": "Sagittarius", "planet": "Jupiter", "quality": "Philosophical destruction, transformative wisdom"},
            {"pada": 2, "navamsa_sign": "Capricorn", "planet": "Saturn", "quality": "Practical perseverance through hardship"},
            {"pada": 3, "navamsa_sign": "Aquarius", "planet": "Saturn", "quality": "Scientific innovation, humanitarian reform"},
            {"pada": 4, "navamsa_sign": "Pisces", "planet": "Jupiter", "quality": "Emotional catharsis, compassionate transformation"},
        ],
        "activation": "Worship Lord Shiva as Rudra. Perform Rudra Abhisheka. Chant Rahu mantras on Saturdays. Practice intense physical exercise or martial arts. Embrace storms and rain as spiritual cleansing.",
        "remedy": {
            "deity_worship": "Worship Rudra (Shiva) with Bilva leaves and perform Rudra Abhisheka",
            "mantra": "Om Rudraya Namah",
            "gemstone": "Hessonite Garnet (Gomed)",
            "donation": "Donate blue/black clothes, mustard oil, and urad dal on Saturdays",
            "fasting": "Saturday",
            "color_therapy": "Green",
            "plant_remedy": "Burn Agar (Agarwood) incense for calming the mind and spiritual purification",
        },
        "special_power": "Yatna Shakti (power of effort and struggle that brings achievement)",
        "description": "Ardra is the storm star of transformation and destruction. Its natives experience intense emotional upheavals that ultimately lead to profound intellectual and spiritual breakthroughs.",
        "description_hi": "आर्द्रा तूफान और परिवर्तन का नक्षत्र है। इसके जातक गहन भावनात्मक उथल-पुथल से गुज़रकर बौद्धिक और आध्यात्मिक ऊँचाइयाँ प्राप्त करते हैं।",
    },

    # ─────────────────────────────────────────────────────────────
    # 7. PUNARVASU  (20°00' Gemini – 3°20' Cancer)
    # ─────────────────────────────────────────────────────────────
    "Punarvasu": {
        "deity": "Aditi",
        "deity_hi": "अदिति",
        "lord": "Jupiter",
        "symbol": "Bow and Quiver",
        "symbol_hi": "धनुष और तरकश",
        "animal_yoni": "Cat (Female)",
        "animal_yoni_hi": "बिल्ली (स्त्री)",
        "gana": "Deva",
        "guna": "Sattva",
        "tattva": "Water",
        "caste": "Vaishya",
        "gender": "Male",
        "nadi": "Aadi",
        "color": "Lead/Grey",
        "bird": "Swan",
        "tree": "Bamboo",
        "tree_botanical": "Bambusa arundinacea",
        "body_part": "Fingers/Nose",
        "direction": "North",
        "motivation": "Artha",
        "temperament": "Movable (Chara)",
        "pada_syllables": ["Ke", "Ko", "Ha", "Hi"],
        "pada_details": [
            {"pada": 1, "navamsa_sign": "Aries", "planet": "Mars", "quality": "Adventurous renewal, active restoration"},
            {"pada": 2, "navamsa_sign": "Taurus", "planet": "Venus", "quality": "Material recovery, stable abundance"},
            {"pada": 3, "navamsa_sign": "Gemini", "planet": "Mercury", "quality": "Intellectual expansion, communicative wisdom"},
            {"pada": 4, "navamsa_sign": "Cancer", "planet": "Moon", "quality": "Emotional renewal, nurturing return home"},
        ],
        "activation": "Worship Goddess Aditi, the cosmic mother. Plant bamboo. Practice gratitude rituals and give thanks for returning blessings. Visit places of pilgrimage. Chant Jupiter mantras on Thursdays.",
        "remedy": {
            "deity_worship": "Worship Aditi Devi with yellow flowers and turmeric",
            "mantra": "Om Aditaye Namah",
            "gemstone": "Yellow Sapphire (Pukhraj)",
            "donation": "Donate yellow items, turmeric, bananas, and books on Thursdays",
            "fasting": "Thursday",
            "color_therapy": "Lead/Grey",
            "plant_remedy": "Keep bamboo plants at home for positive energy and growth",
        },
        "special_power": "Vasutva Prapana Shakti (power to gain wealth and true substance)",
        "description": "Punarvasu is the star of renewal and return. Its natives possess remarkable resilience and the ability to bounce back from any adversity, always finding their way home.",
        "description_hi": "पुनर्वसु नवीनीकरण और वापसी का नक्षत्र है। इसके जातक अत्यंत लचीले होते हैं और हर विपत्ति से उबरने में सक्षम होते हैं।",
    },

    # ─────────────────────────────────────────────────────────────
    # 8. PUSHYA  (3°20' – 16°40' Cancer)
    # ─────────────────────────────────────────────────────────────
    "Pushya": {
        "deity": "Brihaspati",
        "deity_hi": "बृहस्पति",
        "lord": "Saturn",
        "symbol": "Lotus/Circle/Arrow",
        "symbol_hi": "कमल/वृत्त/बाण",
        "animal_yoni": "Goat (Male)",
        "animal_yoni_hi": "बकरा (पुरुष)",
        "gana": "Deva",
        "guna": "Sattva",
        "tattva": "Water",
        "caste": "Vaishya",
        "gender": "Male",
        "nadi": "Madhya",
        "color": "Black",
        "bird": "Crow",
        "tree": "Peepal (Sacred Fig)",
        "tree_botanical": "Ficus religiosa",
        "body_part": "Mouth/Face",
        "direction": "East",
        "motivation": "Dharma",
        "temperament": "Light (Laghu/Kshipra)",
        "pada_syllables": ["Hu", "He", "Ho", "Da"],
        "pada_details": [
            {"pada": 1, "navamsa_sign": "Leo", "planet": "Sun", "quality": "Royal nourishment, generous leadership"},
            {"pada": 2, "navamsa_sign": "Virgo", "planet": "Mercury", "quality": "Service-oriented care, practical nourishment"},
            {"pada": 3, "navamsa_sign": "Libra", "planet": "Venus", "quality": "Harmonious support, aesthetic nurturing"},
            {"pada": 4, "navamsa_sign": "Scorpio", "planet": "Mars", "quality": "Intense devotion, transformative spiritual nourishment"},
        ],
        "activation": "Worship Lord Brihaspati (Jupiter). Visit temples on Thursdays. Feed Brahmins and priests. Start new ventures on Pushya Nakshatra days (considered most auspicious). Meditate under a Peepal tree.",
        "remedy": {
            "deity_worship": "Worship Brihaspati with yellow flowers and offerings of turmeric and ghee",
            "mantra": "Om Brihaspataye Namah",
            "gemstone": "Blue Sapphire (Neelam)",
            "donation": "Donate iron, sesame, and black cloth on Saturdays",
            "fasting": "Saturday",
            "color_therapy": "Black",
            "plant_remedy": "Meditate or sit under a Peepal tree on Saturdays and Thursdays",
        },
        "special_power": "Brahmavarchasa Shakti (power of spiritual energy and priestly brilliance)",
        "description": "Pushya is considered the most auspicious nakshatra for initiating endeavors. Its natives are deeply nurturing, spiritually inclined, and serve as pillars of support for their communities.",
        "description_hi": "पुष्य सबसे शुभ नक्षत्र माना जाता है। इसके जातक पोषणकारी, आध्यात्मिक और समाज के स्तंभ होते हैं।",
    },

    # ─────────────────────────────────────────────────────────────
    # 9. ASHLESHA  (16°40' – 30°00' Cancer)
    # ─────────────────────────────────────────────────────────────
    "Ashlesha": {
        "deity": "Sarpa (Nagas)",
        "deity_hi": "सर्प (नाग देवता)",
        "lord": "Mercury",
        "symbol": "Coiled Serpent",
        "symbol_hi": "कुंडलित सर्प",
        "animal_yoni": "Cat (Male)",
        "animal_yoni_hi": "बिल्ला (पुरुष)",
        "gana": "Rakshasa",
        "guna": "Tamas",
        "tattva": "Water",
        "caste": "Shudra",
        "gender": "Female",
        "nadi": "Antya",
        "color": "Black",
        "bird": "Owl",
        "tree": "Nag Champa/Alexandrian Laurel",
        "tree_botanical": "Calophyllum inophyllum",
        "body_part": "Ears/Nails",
        "direction": "South",
        "motivation": "Dharma",
        "temperament": "Sharp (Tikshna)",
        "pada_syllables": ["Di", "Du", "De", "Do"],
        "pada_details": [
            {"pada": 1, "navamsa_sign": "Sagittarius", "planet": "Jupiter", "quality": "Philosophical wisdom, hidden knowledge"},
            {"pada": 2, "navamsa_sign": "Capricorn", "planet": "Saturn", "quality": "Ambitious scheming, strategic power"},
            {"pada": 3, "navamsa_sign": "Aquarius", "planet": "Saturn", "quality": "Unconventional intellect, mystical research"},
            {"pada": 4, "navamsa_sign": "Pisces", "planet": "Jupiter", "quality": "Spiritual transcendence, intuitive depth"},
        ],
        "activation": "Worship Nagas (Serpent deities). Visit Naga temples. Offer milk to serpent stones (Naga Pratima) on Naga Panchami. Chant Rahu mantras on Saturdays. Practice Kundalini meditation.",
        "remedy": {
            "deity_worship": "Worship Naga Devatas; offer milk and turmeric to Naga stones",
            "mantra": "Om Namo Nagarajaya Namah",
            "gemstone": "Emerald (Panna)",
            "donation": "Donate green items, moong dal, and feed serpents milk on Naga Panchami",
            "fasting": "Wednesday",
            "color_therapy": "Black",
            "plant_remedy": "Use Nag Champa incense in daily worship for protection and spiritual clarity",
        },
        "special_power": "Visasleshana Shakti (power to inflict poison and to destroy the victim)",
        "description": "Ashlesha is the serpent star of mystical wisdom and cunning intelligence. Its natives possess hypnotic charisma, deep psychological insight, and the ability to both heal and harm with their words.",
        "description_hi": "आश्लेषा गूढ़ ज्ञान और तीक्ष्ण बुद्धि का नक्षत्र है। इसके जातक सम्मोहक, मनोवैज्ञानिक और वाक्-शक्ति में निपुण होते हैं।",
    },

    # ─────────────────────────────────────────────────────────────
    # 10. MAGHA  (0°00' – 13°20' Leo)
    # ─────────────────────────────────────────────────────────────
    "Magha": {
        "deity": "Pitris (Ancestors)",
        "deity_hi": "पितृ",
        "lord": "Ketu",
        "symbol": "Royal Throne",
        "symbol_hi": "राजसिंहासन",
        "animal_yoni": "Rat (Male)",
        "animal_yoni_hi": "चूहा (पुरुष)",
        "gana": "Rakshasa",
        "guna": "Tamas",
        "tattva": "Water",
        "caste": "Kshatriya",
        "gender": "Female",
        "nadi": "Antya",
        "color": "Cream/Ivory",
        "bird": "Eagle",
        "tree": "Banyan (Vat Vriksha)",
        "tree_botanical": "Ficus benghalensis",
        "body_part": "Chin/Lips",
        "direction": "West",
        "motivation": "Artha",
        "temperament": "Fierce (Ugra/Krura)",
        "pada_syllables": ["Ma", "Mi", "Mu", "Me"],
        "pada_details": [
            {"pada": 1, "navamsa_sign": "Aries", "planet": "Mars", "quality": "Royal courage, pioneering leadership"},
            {"pada": 2, "navamsa_sign": "Taurus", "planet": "Venus", "quality": "Inherited wealth, ancestral property"},
            {"pada": 3, "navamsa_sign": "Gemini", "planet": "Mercury", "quality": "Intellectual legacy, communicating tradition"},
            {"pada": 4, "navamsa_sign": "Cancer", "planet": "Moon", "quality": "Emotional connection to lineage, maternal ancestry"},
        ],
        "activation": "Honor ancestors (Pitri Tarpana). Sit on a royal chair or elevated seat during meditation. Perform Shraddha ceremony. Donate to the elderly. Visit ancestral homes and maintain family traditions.",
        "remedy": {
            "deity_worship": "Perform Pitri Puja and Tarpana at sacred rivers or temples",
            "mantra": "Om Pitrubhyah Namah",
            "gemstone": "Cat's Eye (Lehsunia)",
            "donation": "Donate blankets, sesame seeds, and food to ancestors' names",
            "fasting": "Tuesday",
            "color_therapy": "Cream/Ivory",
            "plant_remedy": "Worship and circumambulate a Banyan tree on Saturdays for ancestral blessings",
        },
        "special_power": "Tyage Kshepani Shakti (power to leave the body, connect with ancestors)",
        "description": "Magha is the royal star of ancestral power and authority. Its natives carry a regal bearing, deep respect for tradition and lineage, and a natural sense of command and privilege.",
        "description_hi": "मघा राजसी गरिमा और पैतृक शक्ति का नक्षत्र है। इसके जातक परंपरा, वंश और अधिकार की गहरी समझ रखते हैं।",
    },

    # ─────────────────────────────────────────────────────────────
    # 11. PURVA PHALGUNI  (13°20' – 26°40' Leo)
    # ─────────────────────────────────────────────────────────────
    "Purva Phalguni": {
        "deity": "Bhaga",
        "deity_hi": "भग",
        "lord": "Venus",
        "symbol": "Front Legs of Bed/Hammock",
        "symbol_hi": "पलंग के अगले पाए/झूला",
        "animal_yoni": "Rat (Female)",
        "animal_yoni_hi": "चुहिया (स्त्री)",
        "gana": "Manushya",
        "guna": "Rajas",
        "tattva": "Water",
        "caste": "Kshatriya",
        "gender": "Female",
        "nadi": "Madhya",
        "color": "Light Brown",
        "bird": "Peacock",
        "tree": "Palash/Flame of the Forest",
        "tree_botanical": "Butea monosperma",
        "body_part": "Right Hand/Genitals",
        "direction": "North",
        "motivation": "Kama",
        "temperament": "Fierce (Ugra/Krura)",
        "pada_syllables": ["Mo", "Ta", "Ti", "Tu"],
        "pada_details": [
            {"pada": 1, "navamsa_sign": "Leo", "planet": "Sun", "quality": "Creative self-expression, dramatic artistry"},
            {"pada": 2, "navamsa_sign": "Virgo", "planet": "Mercury", "quality": "Refined taste, practical creativity"},
            {"pada": 3, "navamsa_sign": "Libra", "planet": "Venus", "quality": "Romantic partnerships, aesthetic luxury"},
            {"pada": 4, "navamsa_sign": "Scorpio", "planet": "Mars", "quality": "Passionate intensity, deep sensual nature"},
        ],
        "activation": "Worship Bhaga, the deity of conjugal bliss and fortune. Engage in creative arts — music, dance, painting. Rest on a decorated bed or hammock. Perform fertility rituals. Celebrate love and beauty on Fridays.",
        "remedy": {
            "deity_worship": "Worship Bhaga Deva with red and pink flowers, offer sweets",
            "mantra": "Om Bhagaya Namah",
            "gemstone": "Diamond or White Sapphire",
            "donation": "Donate silk clothes, sugar, and perfumes on Fridays",
            "fasting": "Friday",
            "color_therapy": "Light Brown",
            "plant_remedy": "Use Palash flowers for Holi celebrations and in worship for marital bliss",
        },
        "special_power": "Prajanana Shakti (power of procreation and creative generation)",
        "description": "Purva Phalguni is the star of love, pleasure, and creative enjoyment. Its natives are charismatic, artistic, and seek comfort, romance, and the finer things in life.",
        "description_hi": "पूर्वा फाल्गुनी प्रेम, आनंद और सृजन का नक्षत्र है। इसके जातक आकर्षक, कलात्मक और सुख-विलास प्रेमी होते हैं।",
    },

    # ─────────────────────────────────────────────────────────────
    # 12. UTTARA PHALGUNI  (26°40' Leo – 10°00' Virgo)
    # ─────────────────────────────────────────────────────────────
    "Uttara Phalguni": {
        "deity": "Aryaman",
        "deity_hi": "अर्यमन",
        "lord": "Sun",
        "symbol": "Rear Legs of Bed",
        "symbol_hi": "पलंग के पिछले पाए",
        "animal_yoni": "Cow (Male)",
        "animal_yoni_hi": "बैल (पुरुष)",
        "gana": "Manushya",
        "guna": "Rajas",
        "tattva": "Fire",
        "caste": "Vaishya",
        "gender": "Female",
        "nadi": "Aadi",
        "color": "Bright Blue",
        "bird": "Rooster",
        "tree": "Rose Laurel/Payari Fig",
        "tree_botanical": "Ficus arnottiana",
        "body_part": "Left Hand/Spine",
        "direction": "East",
        "motivation": "Moksha",
        "temperament": "Fixed (Dhruva)",
        "pada_syllables": ["Te", "To", "Pa", "Pi"],
        "pada_details": [
            {"pada": 1, "navamsa_sign": "Sagittarius", "planet": "Jupiter", "quality": "Generous patronage, philosophical leadership"},
            {"pada": 2, "navamsa_sign": "Capricorn", "planet": "Saturn", "quality": "Structured commitment, disciplined partnerships"},
            {"pada": 3, "navamsa_sign": "Aquarius", "planet": "Saturn", "quality": "Humanitarian service, social contracts"},
            {"pada": 4, "navamsa_sign": "Pisces", "planet": "Jupiter", "quality": "Spiritual unions, compassionate commitment"},
        ],
        "activation": "Worship Aryaman, deity of friendship and contracts. Strengthen friendships and alliances. Honor marriage vows. Perform Sun worship at noon. Engage in charitable social service.",
        "remedy": {
            "deity_worship": "Worship Aryaman with red lotus and offer ghee in fire rituals",
            "mantra": "Om Aryamne Namah",
            "gemstone": "Ruby (Manik)",
            "donation": "Donate wheat, jaggery, and copper vessels on Sundays",
            "fasting": "Sunday",
            "color_therapy": "Bright Blue",
            "plant_remedy": "Plant and tend a Payari Fig tree; use its shade for meditation",
        },
        "special_power": "Chayani Shakti (power of accumulation through marriage and partnerships)",
        "description": "Uttara Phalguni is the star of patronage and lasting partnerships. Its natives excel in forming enduring alliances, social contracts, and are known for their reliability and warm friendliness.",
        "description_hi": "उत्तरा फाल्गुनी संरक्षण और स्थायी संबंधों का नक्षत्र है। इसके जातक विश्वसनीय, मैत्रीपूर्ण और सामाजिक बंधन बनाने में निपुण होते हैं।",
    },

    # ─────────────────────────────────────────────────────────────
    # 13. HASTA  (10°00' – 23°20' Virgo)
    # ─────────────────────────────────────────────────────────────
    "Hasta": {
        "deity": "Savitar",
        "deity_hi": "सवितार",
        "lord": "Moon",
        "symbol": "Open Hand/Fist",
        "symbol_hi": "खुला हाथ/मुट्ठी",
        "animal_yoni": "Buffalo (Female)",
        "animal_yoni_hi": "भैंस (स्त्री)",
        "gana": "Deva",
        "guna": "Rajas",
        "tattva": "Fire",
        "caste": "Shudra",
        "gender": "Male",
        "nadi": "Aadi",
        "color": "Green",
        "bird": "Crow",
        "tree": "Hog Plum",
        "tree_botanical": "Spondias pinnata",
        "body_part": "Hands/Fingers",
        "direction": "South",
        "motivation": "Moksha",
        "temperament": "Light (Laghu/Kshipra)",
        "pada_syllables": ["Pu", "Sha", "Na", "Tha"],
        "pada_details": [
            {"pada": 1, "navamsa_sign": "Aries", "planet": "Mars", "quality": "Skilled craftsmanship, bold handiwork"},
            {"pada": 2, "navamsa_sign": "Taurus", "planet": "Venus", "quality": "Practical artistry, material dexterity"},
            {"pada": 3, "navamsa_sign": "Gemini", "planet": "Mercury", "quality": "Clever communication, trading skill"},
            {"pada": 4, "navamsa_sign": "Cancer", "planet": "Moon", "quality": "Emotional sensitivity, healing touch"},
        ],
        "activation": "Worship Savitar (the creative Sun deity). Practice hand-based crafts — pottery, painting, healing arts. Recite Gayatri Mantra at sunrise. Use hand mudras during meditation. Develop manual dexterity.",
        "remedy": {
            "deity_worship": "Worship Savitar through Gayatri Mantra at sunrise and sunset",
            "mantra": "Om Savitre Namah (also Gayatri Mantra)",
            "gemstone": "Pearl (Moti)",
            "donation": "Donate white rice, curd, and silver on Mondays",
            "fasting": "Monday",
            "color_therapy": "Green",
            "plant_remedy": "Use Hog Plum fruit or consume it regularly for health benefits",
        },
        "special_power": "Hasta Sthapaniya Agama Shakti (power to gain what one seeks and place it in one's hands)",
        "description": "Hasta is the star of skill and dexterity. Its natives are masterful craftspeople, magicians of the hand, with an innate ability to manifest their desires through effort and cleverness.",
        "description_hi": "हस्त कौशल और निपुणता का नक्षत्र है। इसके जातक हस्तकला, जादू और अपने प्रयासों से इच्छाओं को साकार करने में माहिर होते हैं।",
    },

    # ─────────────────────────────────────────────────────────────
    # 14. CHITRA  (23°20' Virgo – 6°40' Libra)
    # ─────────────────────────────────────────────────────────────
    "Chitra": {
        "deity": "Tvashtar (Vishwakarma)",
        "deity_hi": "त्वष्टा (विश्वकर्मा)",
        "lord": "Mars",
        "symbol": "Bright Jewel/Pearl",
        "symbol_hi": "चमकता रत्न/मोती",
        "animal_yoni": "Tiger (Female)",
        "animal_yoni_hi": "बाघिन (स्त्री)",
        "gana": "Rakshasa",
        "guna": "Tamas",
        "tattva": "Fire",
        "caste": "Shudra",
        "gender": "Female",
        "nadi": "Madhya",
        "color": "Black",
        "bird": "Woodpecker",
        "tree": "Bilva/Bael",
        "tree_botanical": "Aegle marmelos",
        "body_part": "Forehead/Neck",
        "direction": "West",
        "motivation": "Kama",
        "temperament": "Soft (Mridu)",
        "pada_syllables": ["Pe", "Po", "Ra", "Ri"],
        "pada_details": [
            {"pada": 1, "navamsa_sign": "Leo", "planet": "Sun", "quality": "Brilliant self-expression, radiant creativity"},
            {"pada": 2, "navamsa_sign": "Virgo", "planet": "Mercury", "quality": "Precision craftsmanship, meticulous design"},
            {"pada": 3, "navamsa_sign": "Libra", "planet": "Venus", "quality": "Artistic harmony, beauty in relationships"},
            {"pada": 4, "navamsa_sign": "Scorpio", "planet": "Mars", "quality": "Hidden beauty, transformative artistic vision"},
        ],
        "activation": "Worship Tvashtar/Vishwakarma, the celestial architect. Engage in architecture, design, or visual arts. Wear beautiful jewels and adornments. Celebrate Vishwakarma Puja. Create something beautiful on Chitra days.",
        "remedy": {
            "deity_worship": "Worship Vishwakarma with tools and craft offerings; perform Mars puja",
            "mantra": "Om Twashtre Namah",
            "gemstone": "Red Coral (Moonga)",
            "donation": "Donate red lentils, weapons (symbolic), and iron items on Tuesdays",
            "fasting": "Tuesday",
            "color_therapy": "Black",
            "plant_remedy": "Offer Bilva (Bael) leaves to Lord Shiva; consume Bael fruit for health",
        },
        "special_power": "Punya Chayani Shakti (power to accumulate merit in life)",
        "description": "Chitra is the star of brilliant craftsmanship and celestial architecture. Its natives are visually gifted, with a keen eye for beauty, form, and design that creates lasting masterpieces.",
        "description_hi": "चित्रा दिव्य शिल्पकला और सौंदर्य का नक्षत्र है। इसके जातक सुंदरता, रूप और डिजाइन में असाधारण प्रतिभा रखते हैं।",
    },

    # ─────────────────────────────────────────────────────────────
    # 15. SWATI  (6°40' – 20°00' Libra)
    # ─────────────────────────────────────────────────────────────
    "Swati": {
        "deity": "Vayu",
        "deity_hi": "वायु",
        "lord": "Rahu",
        "symbol": "Young Plant Shoot/Coral",
        "symbol_hi": "अंकुर/मूंगा",
        "animal_yoni": "Buffalo (Male)",
        "animal_yoni_hi": "भैंसा (पुरुष)",
        "gana": "Deva",
        "guna": "Sattva",
        "tattva": "Fire",
        "caste": "Shudra",
        "gender": "Female",
        "nadi": "Antya",
        "color": "Black",
        "bird": "Swan",
        "tree": "Arjuna Tree",
        "tree_botanical": "Terminalia arjuna",
        "body_part": "Chest/Breast",
        "direction": "North",
        "motivation": "Artha",
        "temperament": "Movable (Chara)",
        "pada_syllables": ["Ru", "Re", "Ro", "Ta"],
        "pada_details": [
            {"pada": 1, "navamsa_sign": "Sagittarius", "planet": "Jupiter", "quality": "Philosophical independence, expansive freedom"},
            {"pada": 2, "navamsa_sign": "Capricorn", "planet": "Saturn", "quality": "Grounded flexibility, practical independence"},
            {"pada": 3, "navamsa_sign": "Aquarius", "planet": "Saturn", "quality": "Innovative thinking, humanitarian freedom"},
            {"pada": 4, "navamsa_sign": "Pisces", "planet": "Jupiter", "quality": "Spiritual flexibility, compassionate adaptability"},
        ],
        "activation": "Worship Vayu (Wind deity). Practice pranayama (breath work) daily. Spend time outdoors in open, windy spaces. Engage in trade and commerce. Chant Rahu mantras. Plant young saplings and watch them grow.",
        "remedy": {
            "deity_worship": "Worship Vayu Deva with incense and offer prayers in open air",
            "mantra": "Om Vayave Namah",
            "gemstone": "Hessonite Garnet (Gomed)",
            "donation": "Donate dark blue/black cloth and mustard oil on Saturdays",
            "fasting": "Saturday",
            "color_therapy": "Black",
            "plant_remedy": "Use Arjuna bark decoction for heart health; plant Arjuna trees",
        },
        "special_power": "Pradhvamsa Shakti (power to scatter and disperse like the wind)",
        "description": "Swati is the independent star of the wind, symbolizing freedom and flexibility. Its natives are self-reliant, diplomatic, and possess the ability to adapt and thrive in any environment like a resilient young plant.",
        "description_hi": "स्वाति वायु और स्वतंत्रता का नक्षत्र है। इसके जातक आत्मनिर्भर, कूटनीतिक और हर परिस्थिति में ढलने में सक्षम होते हैं।",
    },

    # ─────────────────────────────────────────────────────────────
    # 16. VISHAKHA  (20°00' Libra – 3°20' Scorpio)
    # ─────────────────────────────────────────────────────────────
    "Vishakha": {
        "deity": "Indra-Agni",
        "deity_hi": "इन्द्र-अग्नि",
        "lord": "Jupiter",
        "symbol": "Triumphal Arch/Potter's Wheel",
        "symbol_hi": "विजय तोरण/कुम्हार का चक्र",
        "animal_yoni": "Tiger (Male)",
        "animal_yoni_hi": "बाघ (पुरुष)",
        "gana": "Rakshasa",
        "guna": "Sattva",
        "tattva": "Fire",
        "caste": "Brahmin",
        "gender": "Female",
        "nadi": "Antya",
        "color": "Golden",
        "bird": "Sparrow",
        "tree": "Vikankatha/Nagkesar",
        "tree_botanical": "Mesua ferrea",
        "body_part": "Arms/Breast",
        "direction": "East",
        "motivation": "Dharma",
        "temperament": "Mixed (Mishra/Sadharana)",
        "pada_syllables": ["Ti", "Tu", "Te", "To"],
        "pada_details": [
            {"pada": 1, "navamsa_sign": "Aries", "planet": "Mars", "quality": "Aggressive goal-setting, fiery determination"},
            {"pada": 2, "navamsa_sign": "Taurus", "planet": "Venus", "quality": "Patient perseverance, material ambition"},
            {"pada": 3, "navamsa_sign": "Gemini", "planet": "Mercury", "quality": "Strategic communication, intellectual ambition"},
            {"pada": 4, "navamsa_sign": "Cancer", "planet": "Moon", "quality": "Emotional intensity of purpose, obsessive nurturing"},
        ],
        "activation": "Worship Indra and Agni together. Perform fire ceremonies for achieving goals. Set ambitious targets and pursue them single-mindedly. Practice archery or target-focused activities. Celebrate victories with humility.",
        "remedy": {
            "deity_worship": "Worship Indra-Agni with combined fire and water rituals",
            "mantra": "Om Indragnibhyam Namah",
            "gemstone": "Yellow Sapphire (Pukhraj)",
            "donation": "Donate yellow items, books, and turmeric on Thursdays",
            "fasting": "Thursday",
            "color_therapy": "Golden",
            "plant_remedy": "Use Nagkesar (Mesua ferrea) flower in worship and its oil for skin care",
        },
        "special_power": "Vyapana Shakti (power to achieve many and various fruits in life)",
        "description": "Vishakha is the star of purpose and determination, the tireless achiever. Its natives are intensely goal-oriented, possessing a single-pointed focus that drives them to triumph through any obstacle.",
        "description_hi": "विशाखा संकल्प और दृढ़ निश्चय का नक्षत्र है। इसके जातक लक्ष्य-केंद्रित, अथक और हर बाधा को पार करने वाले होते हैं।",
    },

    # ─────────────────────────────────────────────────────────────
    # 17. ANURADHA  (3°20' – 16°40' Scorpio)
    # ─────────────────────────────────────────────────────────────
    "Anuradha": {
        "deity": "Mitra",
        "deity_hi": "मित्र",
        "lord": "Saturn",
        "symbol": "Lotus/Staff",
        "symbol_hi": "कमल/दंड",
        "animal_yoni": "Deer (Female)",
        "animal_yoni_hi": "हिरनी (स्त्री)",
        "gana": "Deva",
        "guna": "Sattva",
        "tattva": "Fire",
        "caste": "Vaishya",
        "gender": "Male",
        "nadi": "Madhya",
        "color": "Reddish Brown",
        "bird": "Pigeon",
        "tree": "Maulsiri/Bakula",
        "tree_botanical": "Mimusops elengi",
        "body_part": "Stomach/Chest",
        "direction": "South",
        "motivation": "Dharma",
        "temperament": "Soft (Mridu)",
        "pada_syllables": ["Na", "Ni", "Nu", "Ne"],
        "pada_details": [
            {"pada": 1, "navamsa_sign": "Leo", "planet": "Sun", "quality": "Loyal leadership, radiant friendship"},
            {"pada": 2, "navamsa_sign": "Virgo", "planet": "Mercury", "quality": "Analytical devotion, service through friendship"},
            {"pada": 3, "navamsa_sign": "Libra", "planet": "Venus", "quality": "Harmonious partnerships, artistic collaboration"},
            {"pada": 4, "navamsa_sign": "Scorpio", "planet": "Mars", "quality": "Deep emotional bonds, transformative loyalty"},
        ],
        "activation": "Worship Mitra, the deity of friendship and cosmic harmony. Build genuine friendships and honor alliances. Practice devotional singing (bhajan/kirtan). Visit sacred rivers and lotus ponds. Perform Saturn remedies on Saturdays.",
        "remedy": {
            "deity_worship": "Worship Mitra Deva with lotus flowers and friendship offerings",
            "mantra": "Om Mitraya Namah",
            "gemstone": "Blue Sapphire (Neelam)",
            "donation": "Donate iron utensils, black sesame, and oil on Saturdays",
            "fasting": "Saturday",
            "color_therapy": "Reddish Brown",
            "plant_remedy": "Plant Bakula (Mimusops elengi) tree; use its fragrant flowers in worship",
        },
        "special_power": "Radhana Shakti (power of worship, devotion, and forming lasting bonds)",
        "description": "Anuradha is the star of devotion and friendship. Its natives form deep, lasting bonds of loyalty and succeed through collaborative effort, devotion, and the ability to thrive in foreign lands.",
        "description_hi": "अनुराधा भक्ति और मित्रता का नक्षत्र है। इसके जातक गहरे बंधन बनाते हैं और सहयोग व समर्पण से सफलता पाते हैं।",
    },

    # ─────────────────────────────────────────────────────────────
    # 18. JYESHTHA  (16°40' – 30°00' Scorpio)
    # ─────────────────────────────────────────────────────────────
    "Jyeshtha": {
        "deity": "Indra",
        "deity_hi": "इन्द्र",
        "lord": "Mercury",
        "symbol": "Circular Amulet/Earring",
        "symbol_hi": "गोलाकार ताबीज/कुंडल",
        "animal_yoni": "Deer (Male)",
        "animal_yoni_hi": "हिरन (पुरुष)",
        "gana": "Rakshasa",
        "guna": "Sattva",
        "tattva": "Air",
        "caste": "Shudra",
        "gender": "Female",
        "nadi": "Aadi",
        "color": "Cream",
        "bird": "Rooster",
        "tree": "Neem",
        "tree_botanical": "Azadirachta indica",
        "body_part": "Right Side/Neck",
        "direction": "West",
        "motivation": "Artha",
        "temperament": "Sharp (Tikshna)",
        "pada_syllables": ["No", "Ya", "Yi", "Yu"],
        "pada_details": [
            {"pada": 1, "navamsa_sign": "Sagittarius", "planet": "Jupiter", "quality": "Wise authority, righteous power"},
            {"pada": 2, "navamsa_sign": "Capricorn", "planet": "Saturn", "quality": "Responsible leadership, structured dominance"},
            {"pada": 3, "navamsa_sign": "Aquarius", "planet": "Saturn", "quality": "Humanitarian authority, unconventional power"},
            {"pada": 4, "navamsa_sign": "Pisces", "planet": "Jupiter", "quality": "Spiritual leadership, compassionate authority"},
        ],
        "activation": "Worship Indra, king of the gods. Wear a protective amulet or earring. Practice leadership and take on elder responsibilities. Perform Mercury rituals on Wednesdays. Use Neem for purification rituals.",
        "remedy": {
            "deity_worship": "Worship Indra Deva with white flowers and perform rain/water rituals",
            "mantra": "Om Indraya Namah",
            "gemstone": "Emerald (Panna)",
            "donation": "Donate green moong, books, and educational materials on Wednesdays",
            "fasting": "Wednesday",
            "color_therapy": "Cream",
            "plant_remedy": "Use Neem leaves in bathing water for purification; chew Neem twigs for dental health",
        },
        "special_power": "Arohana Shakti (power to rise, conquer, and gain supremacy)",
        "description": "Jyeshtha is the star of the eldest and most powerful. Its natives possess natural authority, protective instincts, and the courage to defend what is right, often bearing heavy responsibilities.",
        "description_hi": "ज्येष्ठा सबसे बड़े और सबसे शक्तिशाली का नक्षत्र है। इसके जातक स्वाभाविक अधिकारी, रक्षक और बड़ी ज़िम्मेदारियाँ उठाने वाले होते हैं।",
    },

    # ─────────────────────────────────────────────────────────────
    # 19. MULA  (0°00' – 13°20' Sagittarius)
    # ─────────────────────────────────────────────────────────────
    "Mula": {
        "deity": "Nirrti",
        "deity_hi": "निऋति",
        "lord": "Ketu",
        "symbol": "Bundle of Roots",
        "symbol_hi": "जड़ों का गुच्छा",
        "animal_yoni": "Dog (Male)",
        "animal_yoni_hi": "कुत्ता (पुरुष)",
        "gana": "Rakshasa",
        "guna": "Tamas",
        "tattva": "Air",
        "caste": "Shudra",
        "gender": "Neutral",
        "nadi": "Aadi",
        "color": "Brownish Yellow",
        "bird": "Cock",
        "tree": "Sal Tree",
        "tree_botanical": "Shorea robusta",
        "body_part": "Feet/Left Side",
        "direction": "North",
        "motivation": "Kama",
        "temperament": "Sharp (Tikshna)",
        "pada_syllables": ["Ye", "Yo", "Bha", "Bhi"],
        "pada_details": [
            {"pada": 1, "navamsa_sign": "Aries", "planet": "Mars", "quality": "Fierce uprooting, courageous destruction of obstacles"},
            {"pada": 2, "navamsa_sign": "Taurus", "planet": "Venus", "quality": "Material investigation, seeking root causes in wealth"},
            {"pada": 3, "navamsa_sign": "Gemini", "planet": "Mercury", "quality": "Intellectual inquiry, research and investigation"},
            {"pada": 4, "navamsa_sign": "Cancer", "planet": "Moon", "quality": "Emotional depth, seeking emotional roots and foundation"},
        ],
        "activation": "Worship Nirrti or Goddess Kali for root-level transformation. Practice deep introspection and shadow work. Visit ancient temples and sacred groves. Perform Ketu remedies. Meditate at the base of old trees to connect with primal roots.",
        "remedy": {
            "deity_worship": "Worship Nirrti/Kali with dark flowers; perform Ketu puja",
            "mantra": "Om Nirrityai Namah",
            "gemstone": "Cat's Eye (Lehsunia)",
            "donation": "Donate multi-colored blankets, root vegetables, and sesame on Tuesdays",
            "fasting": "Tuesday",
            "color_therapy": "Brownish Yellow",
            "plant_remedy": "Sit under a Sal tree for grounding; use Sal resin (dhoop) in worship",
        },
        "special_power": "Barhana Shakti (power to destroy, uproot, and break things apart)",
        "description": "Mula is the star of roots and radical transformation. Its natives possess the power to penetrate to the deepest core of any matter, destroying illusions to reach fundamental truth.",
        "description_hi": "मूल जड़ और आमूल परिवर्तन का नक्षत्र है। इसके जातक किसी भी विषय की गहराई में जाकर भ्रम को नष्ट कर मूल सत्य तक पहुँचते हैं।",
    },

    # ─────────────────────────────────────────────────────────────
    # 20. PURVA ASHADHA  (13°20' – 26°40' Sagittarius)
    # ─────────────────────────────────────────────────────────────
    "Purva Ashadha": {
        "deity": "Apas (Water deity)",
        "deity_hi": "अपस (जल देवता)",
        "lord": "Venus",
        "symbol": "Winnowing Fan/Elephant Tusk",
        "symbol_hi": "सूप/हाथी का दाँत",
        "animal_yoni": "Monkey (Male)",
        "animal_yoni_hi": "बंदर (पुरुष)",
        "gana": "Manushya",
        "guna": "Rajas",
        "tattva": "Air",
        "caste": "Brahmin",
        "gender": "Female",
        "nadi": "Madhya",
        "color": "Black",
        "bird": "Francolin",
        "tree": "Rattan Cane",
        "tree_botanical": "Calamus rotang",
        "body_part": "Thighs/Back",
        "direction": "East",
        "motivation": "Moksha",
        "temperament": "Fierce (Ugra/Krura)",
        "pada_syllables": ["Bhu", "Dha", "Pha", "Dha"],
        "pada_details": [
            {"pada": 1, "navamsa_sign": "Leo", "planet": "Sun", "quality": "Proud declaration, invincible conviction"},
            {"pada": 2, "navamsa_sign": "Virgo", "planet": "Mercury", "quality": "Analytical persuasion, detailed argumentation"},
            {"pada": 3, "navamsa_sign": "Libra", "planet": "Venus", "quality": "Charismatic diplomacy, artistic victory"},
            {"pada": 4, "navamsa_sign": "Scorpio", "planet": "Mars", "quality": "Intense resolve, hidden power of conviction"},
        ],
        "activation": "Worship Apas (Water deities). Perform water rituals near rivers or the sea. Practice philosophical debate and declarative speech. Engage in purification through water (snana). Offer water to the Sun every morning.",
        "remedy": {
            "deity_worship": "Worship Varuna/Apas with water offerings at sacred rivers",
            "mantra": "Om Apadbhyah Namah",
            "gemstone": "Diamond or White Sapphire",
            "donation": "Donate silk, sugar, and white foods on Fridays",
            "fasting": "Friday",
            "color_therapy": "Black",
            "plant_remedy": "Use Rattan cane products in the home; keep water features for positive energy",
        },
        "special_power": "Varchograhana Shakti (power to energize and invigorate)",
        "description": "Purva Ashadha is the invincible star of declaration and purification. Its natives possess irresistible powers of persuasion, an undefeatable spirit, and the ability to purify and energize through their convictions.",
        "description_hi": "पूर्वाषाढ़ अजेय घोषणा और शुद्धिकरण का नक्षत्र है। इसके जातक अप्रतिरोध्य वाक्शक्ति और अपराजित भावना रखते हैं।",
    },

    # ─────────────────────────────────────────────────────────────
    # 21. UTTARA ASHADHA  (26°40' Sagittarius – 10°00' Capricorn)
    # ─────────────────────────────────────────────────────────────
    "Uttara Ashadha": {
        "deity": "Vishve Devas (Universal Gods)",
        "deity_hi": "विश्वेदेव",
        "lord": "Sun",
        "symbol": "Elephant Tusk/Planks of Bed",
        "symbol_hi": "हाथी दाँत/पलंग के तख्ते",
        "animal_yoni": "Mongoose (Male)",
        "animal_yoni_hi": "नेवला (पुरुष)",
        "gana": "Manushya",
        "guna": "Rajas",
        "tattva": "Air",
        "caste": "Kshatriya",
        "gender": "Female",
        "nadi": "Antya",
        "color": "Copper",
        "bird": "Stork",
        "tree": "Jackfruit",
        "tree_botanical": "Artocarpus heterophyllus",
        "body_part": "Thighs/Waist",
        "direction": "South",
        "motivation": "Moksha",
        "temperament": "Fixed (Dhruva)",
        "pada_syllables": ["Bhe", "Bho", "Ja", "Ji"],
        "pada_details": [
            {"pada": 1, "navamsa_sign": "Sagittarius", "planet": "Jupiter", "quality": "Philosophical leadership, universal vision"},
            {"pada": 2, "navamsa_sign": "Capricorn", "planet": "Saturn", "quality": "Peak authority, disciplined governance"},
            {"pada": 3, "navamsa_sign": "Aquarius", "planet": "Saturn", "quality": "Humanitarian mission, universal service"},
            {"pada": 4, "navamsa_sign": "Pisces", "planet": "Jupiter", "quality": "Spiritual authority, divine governance"},
        ],
        "activation": "Worship Vishve Devas (all the gods together). Practice universal values of truth, patience, and righteousness. Perform Sun worship at noon. Engage in dharmic leadership. Take vows and honor commitments with unwavering resolve.",
        "remedy": {
            "deity_worship": "Worship Vishve Devas and perform multi-deity puja for universal blessings",
            "mantra": "Om Vishvedevabhyo Namah",
            "gemstone": "Ruby (Manik)",
            "donation": "Donate wheat, copper, and red clothes on Sundays",
            "fasting": "Sunday",
            "color_therapy": "Copper",
            "plant_remedy": "Plant a Jackfruit tree; eat Jackfruit as sacred food for strength",
        },
        "special_power": "Apradhrishya Shakti (power of being unchallengeable and invincible)",
        "description": "Uttara Ashadha is the universal star of final victory. Its natives embody righteous leadership, unwavering commitment to universal values, and the endurance to achieve lasting, permanent victory.",
        "description_hi": "उत्तराषाढ़ अंतिम विजय और सार्वभौमिक नेतृत्व का नक्षत्र है। इसके जातक धर्मनिष्ठ, अडिग और स्थायी सफलता प्राप्त करने वाले होते हैं।",
    },

    # ─────────────────────────────────────────────────────────────
    # 22. SHRAVANA  (10°00' – 23°20' Capricorn)
    # ─────────────────────────────────────────────────────────────
    "Shravana": {
        "deity": "Vishnu",
        "deity_hi": "विष्णु",
        "lord": "Moon",
        "symbol": "Three Footprints/Ear",
        "symbol_hi": "तीन पदचिह्न/कान",
        "animal_yoni": "Monkey (Female)",
        "animal_yoni_hi": "बंदरिया (स्त्री)",
        "gana": "Deva",
        "guna": "Rajas",
        "tattva": "Air",
        "caste": "Shudra",
        "gender": "Male",
        "nadi": "Antya",
        "color": "Light Blue",
        "bird": "Rooster",
        "tree": "Arka/Crown Flower",
        "tree_botanical": "Calotropis gigantea",
        "body_part": "Ears/Reproductive",
        "direction": "West",
        "motivation": "Kama",
        "temperament": "Movable (Chara)",
        "pada_syllables": ["Ju/Khi", "Je/Khu", "Jo/Khe", "Gha/Kho"],
        "pada_details": [
            {"pada": 1, "navamsa_sign": "Aries", "planet": "Mars", "quality": "Active listening, pioneering knowledge acquisition"},
            {"pada": 2, "navamsa_sign": "Taurus", "planet": "Venus", "quality": "Musical appreciation, grounded learning"},
            {"pada": 3, "navamsa_sign": "Gemini", "planet": "Mercury", "quality": "Scholarly communication, teaching and transmitting knowledge"},
            {"pada": 4, "navamsa_sign": "Cancer", "planet": "Moon", "quality": "Compassionate listening, emotional wisdom"},
        ],
        "activation": "Worship Lord Vishnu, the all-pervading preserver. Practice deep listening and study of sacred texts. Learn music or recitation of Vedic hymns. Visit Vishnu temples on Mondays. Practice walking meditation (remembering Vishnu's three steps).",
        "remedy": {
            "deity_worship": "Worship Lord Vishnu with tulsi leaves and yellow flowers",
            "mantra": "Om Namo Narayanaya",
            "gemstone": "Pearl (Moti)",
            "donation": "Donate white rice, milk, and silver on Mondays",
            "fasting": "Monday",
            "color_therapy": "Light Blue",
            "plant_remedy": "Use Arka (Calotropis) leaves in Shiva worship; keep away from direct consumption",
        },
        "special_power": "Samhanana Shakti (power of connection, linking people together)",
        "description": "Shravana is the star of listening and learning. Its natives are gifted scholars, counselors, and teachers who acquire knowledge through attentive listening and share wisdom through clear communication.",
        "description_hi": "श्रवण श्रवण और ज्ञान का नक्षत्र है। इसके जातक प्रतिभाशाली विद्वान, परामर्शदाता और ध्यानपूर्वक सुनकर ज्ञान प्राप्त करने वाले होते हैं।",
    },

    # ─────────────────────────────────────────────────────────────
    # 23. DHANISHTHA  (23°20' Capricorn – 6°40' Aquarius)
    # ─────────────────────────────────────────────────────────────
    "Dhanishtha": {
        "deity": "Vasus (Eight Elemental Gods)",
        "deity_hi": "अष्ट वसु",
        "lord": "Mars",
        "symbol": "Drum (Mridanga)",
        "symbol_hi": "मृदंग/ढोल",
        "animal_yoni": "Lion (Female)",
        "animal_yoni_hi": "सिंहनी (स्त्री)",
        "gana": "Rakshasa",
        "guna": "Tamas",
        "tattva": "Ether",
        "caste": "Vaishya",
        "gender": "Female",
        "nadi": "Madhya",
        "color": "Silver",
        "bird": "Golden Bee",
        "tree": "Shami",
        "tree_botanical": "Prosopis cineraria",
        "body_part": "Back/Anus",
        "direction": "North",
        "motivation": "Dharma",
        "temperament": "Movable (Chara)",
        "pada_syllables": ["Ga", "Gi", "Gu", "Ge"],
        "pada_details": [
            {"pada": 1, "navamsa_sign": "Leo", "planet": "Sun", "quality": "Musical brilliance, confident performance"},
            {"pada": 2, "navamsa_sign": "Virgo", "planet": "Mercury", "quality": "Technical musicianship, precision in rhythm"},
            {"pada": 3, "navamsa_sign": "Libra", "planet": "Venus", "quality": "Harmonious wealth, artistic abundance"},
            {"pada": 4, "navamsa_sign": "Scorpio", "planet": "Mars", "quality": "Intense rhythmic power, martial music"},
        ],
        "activation": "Worship the eight Vasus (elemental gods). Play or listen to drum music. Dance to rhythmic beats. Celebrate wealth and abundance with generosity. Worship the Shami tree on Dussehra. Practice group musical activities.",
        "remedy": {
            "deity_worship": "Worship Ashta Vasus with eight types of offerings; perform Mars puja",
            "mantra": "Om Vasubhyo Namah",
            "gemstone": "Red Coral (Moonga)",
            "donation": "Donate red lentils, jaggery, and musical instruments on Tuesdays",
            "fasting": "Tuesday",
            "color_therapy": "Silver",
            "plant_remedy": "Worship the Shami tree; keep its leaves in your purse for wealth",
        },
        "special_power": "Khyapayitri Shakti (power to give abundance and fame)",
        "description": "Dhanishtha is the star of symphony and abundance. Its natives have a natural sense of rhythm, musical talent, and the ability to attract wealth and fame through their vibrant, energetic nature.",
        "description_hi": "धनिष्ठा लय और समृद्धि का नक्षत्र है। इसके जातक संगीत प्रतिभा, धन आकर्षण और ऊर्जावान स्वभाव रखते हैं।",
    },

    # ─────────────────────────────────────────────────────────────
    # 24. SHATABHISHA  (6°40' – 20°00' Aquarius)
    # ─────────────────────────────────────────────────────────────
    "Shatabhisha": {
        "deity": "Varuna",
        "deity_hi": "वरुण",
        "lord": "Rahu",
        "symbol": "Empty Circle/1000 Flowers",
        "symbol_hi": "खाली वृत्त/सहस्र पुष्प",
        "animal_yoni": "Horse (Female)",
        "animal_yoni_hi": "घोड़ी (स्त्री)",
        "gana": "Rakshasa",
        "guna": "Tamas",
        "tattva": "Ether",
        "caste": "Shudra",
        "gender": "Neutral",
        "nadi": "Aadi",
        "color": "Blue-Green",
        "bird": "Raven",
        "tree": "Kadamba",
        "tree_botanical": "Neolamarckia cadamba",
        "body_part": "Jaw/Right Thigh",
        "direction": "South",
        "motivation": "Dharma",
        "temperament": "Movable (Chara)",
        "pada_syllables": ["Go", "Sa", "Si", "Su"],
        "pada_details": [
            {"pada": 1, "navamsa_sign": "Sagittarius", "planet": "Jupiter", "quality": "Philosophical healing, expansive medical vision"},
            {"pada": 2, "navamsa_sign": "Capricorn", "planet": "Saturn", "quality": "Disciplined therapy, systematic healing"},
            {"pada": 3, "navamsa_sign": "Aquarius", "planet": "Saturn", "quality": "Innovative medicine, unconventional cures"},
            {"pada": 4, "navamsa_sign": "Pisces", "planet": "Jupiter", "quality": "Spiritual healing, mystical medicine"},
        ],
        "activation": "Worship Varuna, lord of the cosmic waters. Practice oceanic meditation. Study alternative healing modalities. Perform water rituals at night under the stars. Chant Rahu mantras. Keep an empty circle symbol for meditation on the void.",
        "remedy": {
            "deity_worship": "Worship Varuna Deva with water offerings and blue flowers",
            "mantra": "Om Varunaya Namah",
            "gemstone": "Hessonite Garnet (Gomed)",
            "donation": "Donate blue/black cloth, medicines, and mustard oil on Saturdays",
            "fasting": "Saturday",
            "color_therapy": "Blue-Green",
            "plant_remedy": "Sit under a Kadamba tree for healing energy; use Kadamba bark in Ayurvedic remedies",
        },
        "special_power": "Bheshaja Shakti (power of healing and providing medicines)",
        "description": "Shatabhisha is the star of a hundred healers. Its natives possess extraordinary healing abilities, a veil of mystery, and the capacity to cure through unconventional and mystical methods.",
        "description_hi": "शतभिषा सौ चिकित्सकों का नक्षत्र है। इसके जातक असाधारण चिकित्सा क्षमता और रहस्यमय उपचार शक्ति रखते हैं।",
    },

    # ─────────────────────────────────────────────────────────────
    # 25. PURVA BHADRAPADA  (20°00' Aquarius – 3°20' Pisces)
    # ─────────────────────────────────────────────────────────────
    "Purva Bhadrapada": {
        "deity": "Aja Ekapada",
        "deity_hi": "अज एकपाद",
        "lord": "Jupiter",
        "symbol": "Front of Funeral Cot/Sword",
        "symbol_hi": "अर्थी का अगला भाग/तलवार",
        "animal_yoni": "Lion (Male)",
        "animal_yoni_hi": "सिंह (पुरुष)",
        "gana": "Manushya",
        "guna": "Sattva",
        "tattva": "Ether",
        "caste": "Vaishya",
        "gender": "Male",
        "nadi": "Aadi",
        "color": "Silver Grey",
        "bird": "Eagle",
        "tree": "Mango",
        "tree_botanical": "Mangifera indica",
        "body_part": "Left Thigh/Ribs",
        "direction": "West",
        "motivation": "Artha",
        "temperament": "Fierce (Ugra/Krura)",
        "pada_syllables": ["Se", "So", "Da", "Di"],
        "pada_details": [
            {"pada": 1, "navamsa_sign": "Aries", "planet": "Mars", "quality": "Fiery penance, radical transformation"},
            {"pada": 2, "navamsa_sign": "Taurus", "planet": "Venus", "quality": "Material sacrifice for spiritual gain"},
            {"pada": 3, "navamsa_sign": "Gemini", "planet": "Mercury", "quality": "Intellectual mysticism, esoteric communication"},
            {"pada": 4, "navamsa_sign": "Cancer", "planet": "Moon", "quality": "Emotional purification through austerity"},
        ],
        "activation": "Worship Aja Ekapada (one-footed cosmic being). Practice intense tapasya (penance). Engage in radical spiritual practices. Study occult and mystical texts. Perform Jupiter remedies on Thursdays. Practice standing meditation or one-legged poses.",
        "remedy": {
            "deity_worship": "Worship Aja Ekapada and Lord Shiva with intense devotion",
            "mantra": "Om Aja Ekapadaya Namah",
            "gemstone": "Yellow Sapphire (Pukhraj)",
            "donation": "Donate yellow cloth, turmeric, and sacred books on Thursdays",
            "fasting": "Thursday",
            "color_therapy": "Silver Grey",
            "plant_remedy": "Worship under a Mango tree; offer mango leaves in fire rituals (havan)",
        },
        "special_power": "Yajamana Udyamana Shakti (power to uplift and elevate spiritually)",
        "description": "Purva Bhadrapada is the scorching star of spiritual fire and radical transformation. Its natives are intense, passionate about spiritual evolution, and willing to endure extreme penance for higher truth.",
        "description_hi": "पूर्वा भाद्रपद आध्यात्मिक अग्नि और आमूल परिवर्तन का नक्षत्र है। इसके जातक तीव्र तपस्वी और उच्च सत्य के लिए कठोर साधना करने वाले होते हैं।",
    },

    # ─────────────────────────────────────────────────────────────
    # 26. UTTARA BHADRAPADA  (3°20' – 16°40' Pisces)
    # ─────────────────────────────────────────────────────────────
    "Uttara Bhadrapada": {
        "deity": "Ahir Budhnya",
        "deity_hi": "अहिर्बुध्न्य",
        "lord": "Saturn",
        "symbol": "Back of Funeral Cot/Twin",
        "symbol_hi": "अर्थी का पिछला भाग/जुड़वाँ",
        "animal_yoni": "Cow (Female)",
        "animal_yoni_hi": "गाय (स्त्री)",
        "gana": "Manushya",
        "guna": "Tamas",
        "tattva": "Ether",
        "caste": "Kshatriya",
        "gender": "Male",
        "nadi": "Madhya",
        "color": "Purple",
        "bird": "Pigeon",
        "tree": "Neem",
        "tree_botanical": "Azadirachta indica",
        "body_part": "Shins/Soles",
        "direction": "North",
        "motivation": "Kama",
        "temperament": "Fixed (Dhruva)",
        "pada_syllables": ["Du", "Tha", "Jha", "Da"],
        "pada_details": [
            {"pada": 1, "navamsa_sign": "Leo", "planet": "Sun", "quality": "Illuminated depth, wise authority"},
            {"pada": 2, "navamsa_sign": "Virgo", "planet": "Mercury", "quality": "Analytical wisdom, detailed contemplation"},
            {"pada": 3, "navamsa_sign": "Libra", "planet": "Venus", "quality": "Balanced depth, harmonious compassion"},
            {"pada": 4, "navamsa_sign": "Scorpio", "planet": "Mars", "quality": "Profound transformation, oceanic depth"},
        ],
        "activation": "Worship Ahir Budhnya, the serpent of the deep. Practice deep meditation on cosmic dissolution. Sleep with awareness (Yoga Nidra). Perform Saturn remedies on Saturdays. Cultivate patience and endurance. Serve the elderly and disadvantaged.",
        "remedy": {
            "deity_worship": "Worship Ahir Budhnya and Lord Shiva with water and Bilva leaves",
            "mantra": "Om Ahir Budhnyaya Namah",
            "gemstone": "Blue Sapphire (Neelam)",
            "donation": "Donate iron, black sesame, blue/purple cloth on Saturdays",
            "fasting": "Saturday",
            "color_therapy": "Purple",
            "plant_remedy": "Plant a Neem tree; use Neem oil for protection and healing",
        },
        "special_power": "Varshodyamana Shakti (power to bring rain and cosmic stability)",
        "description": "Uttara Bhadrapada is the deep ocean star of cosmic wisdom and stability. Its natives are profoundly wise, patient, and possess the depth of a still ocean, controlling the cosmic serpent energy within.",
        "description_hi": "उत्तरा भाद्रपद ब्रह्मांडीय ज्ञान और गहराई का नक्षत्र है। इसके जातक गंभीर, धैर्यवान और शांत सागर जैसी गहराई रखते हैं।",
    },

    # ─────────────────────────────────────────────────────────────
    # 27. REVATI  (16°40' – 30°00' Pisces)
    # ─────────────────────────────────────────────────────────────
    "Revati": {
        "deity": "Pushan",
        "deity_hi": "पूषन",
        "lord": "Mercury",
        "symbol": "Fish/Drum",
        "symbol_hi": "मछली/नगाड़ा",
        "animal_yoni": "Elephant (Female)",
        "animal_yoni_hi": "हथिनी (स्त्री)",
        "gana": "Deva",
        "guna": "Sattva",
        "tattva": "Ether",
        "caste": "Vaishya",
        "gender": "Female",
        "nadi": "Antya",
        "color": "Brown",
        "bird": "Elephant (symbolic)",
        "tree": "Madhuca/Mahua",
        "tree_botanical": "Madhuca longifolia",
        "body_part": "Ankles/Abdomen",
        "direction": "East",
        "motivation": "Moksha",
        "temperament": "Soft (Mridu)",
        "pada_syllables": ["De", "Do", "Cha", "Chi"],
        "pada_details": [
            {"pada": 1, "navamsa_sign": "Sagittarius", "planet": "Jupiter", "quality": "Philosophical nourishment, expansive compassion"},
            {"pada": 2, "navamsa_sign": "Capricorn", "planet": "Saturn", "quality": "Structured care, practical nurturing"},
            {"pada": 3, "navamsa_sign": "Aquarius", "planet": "Saturn", "quality": "Humanitarian compassion, universal care"},
            {"pada": 4, "navamsa_sign": "Pisces", "planet": "Jupiter", "quality": "Transcendent nourishment, spiritual completion"},
        ],
        "activation": "Worship Pushan, the nourishing shepherd of souls. Care for animals, especially cows and fish. Practice compassionate living and feed the hungry. Visit pilgrimage sites. Chant Mercury mantras on Wednesdays. Practice guided visualization journeys.",
        "remedy": {
            "deity_worship": "Worship Pushan with offerings of milk, honey, and flowers",
            "mantra": "Om Pushne Namah",
            "gemstone": "Emerald (Panna)",
            "donation": "Donate green items, feed fish, and support animal shelters on Wednesdays",
            "fasting": "Wednesday",
            "color_therapy": "Brown",
            "plant_remedy": "Use Mahua flowers for worship; its oil is beneficial for skin and hair care",
        },
        "special_power": "Kshiradyapani Shakti (power of nourishment and safe travel)",
        "description": "Revati is the final star of nourishment and safe passage. Its natives are gentle, compassionate souls who guide others on their journeys, offering protection and sustenance until the very end of the cosmic cycle.",
        "description_hi": "रेवती पोषण और सुरक्षित मार्गदर्शन का अंतिम नक्षत्र है। इसके जातक कोमल, दयालु और दूसरों को जीवन यात्रा में मार्गदर्शन देने वाले होते हैं।",
    },
}
